### ISSUE TITLE
直接使用首页的那段短码，无法使用么？

### ISSUE THREAD

**Issue by mei-y** [DLTech21/ofd.js#13]
那段短码报错，can not read property symbol.iterator of undefined。
const divs = renderofd(1200,res)这里报错了。

parseOfdDocument({
        ofd: file,
        success(res) {
          //输出ofd每页的div
          const divs = renderOfd(1200, res);
          //获取签章div的信息, 具体看demo
          for(let ele of document.getElementsByName('seal_img_div')) {
             this.addEventOnSealDiv(ele, JSON.parse(ele.dataset.sesSignature), JSON.parse(ele.dataset.signedInfo));
          }
        },
        fail(error) {
          console.log(error)
        }
      });

就是照着这个写的。
renderOfd(screenWidth, res)。这个地方第二个参数，在你src的helloworld.vue里参数是res[0],改掉之后就可以跑了，没有报错。首页那边标错了。

**Comment by DLTech21** [comment]
贴出完整代码

**Comment by DLTech21** [comment]
解析回来的res是个数组
