### ISSUE TITLE
某些OFD文件印章解析失败

### ISSUE THREAD

**Issue by humingzhang** [DLTech21/ofd.js#20]
某些OFD文件印章解析失败
文件地址：https://github.com/minghu-zhang/ofdrw/blob/master/ofdrw-sign/src/test/resources/keyword.ofd

**Comment by roy19831015** [comment]
问题关闭，已解决。
参见以下改动。
https://github.com/DLTech21/ofd.js/commit/5e90a5efb14d9055aba6ca09caf7571d076c1e98

另外，签名并没有处理，暂时只处理了签章。
