### ISSUE TITLE
IE 11 不兼容

### ISSUE THREAD

**Issue by PengKezhu** [DLTech21/ofd.js#22]
1、
![image](https://user-images.githubusercontent.com/24352707/96548536-a5e2a380-12e0-11eb-9174-61fd96f9cfea.png)

2、
![image](https://user-images.githubusercontent.com/24352707/96548567-b135cf00-12e0-11eb-8ee4-3227c7cb3b99.png)

**Comment by DLTech21** [comment]
没考虑要去兼容
