### ISSUE TITLE
签章的z-index存在问题，隐藏在下面，无法显示

### ISSUE THREAD

**Issue by spenggch** [DLTech21/ofd.js#24]

**Comment by roy19831015** [comment]
请提供测试用例。

**Comment by spenggch** [comment]
可以使用附件中的文档进行测试
















在 2020-10-23 07:32:18，"roy19831015" <notifications@github.com> 写道：

请提供测试用例。

**Comment by DLTech21** [comment]
附件呢？

**Comment by spenggch** [comment]
见附件













在 2020-10-23 18:10:54，"Donal" <notifications@github.com> 写道：

附件呢？

**Comment by DLTech21** [comment]
你是邮件的附件，到不了github，邮件上也不会有。。。。。。传到GitHub上

**Comment by spenggch** [comment]
github限制了，不让上传ofd格式的文件，你的邮箱多少，直接传给你










在 2020-10-24 09:02:23，"Donal" <notifications@github.com> 写道：

你是邮件的附件，到不了github，邮件上也不会有。。。。。。传到GitHub上

**Comment by spenggch** [comment]
> 你是邮件的附件，到不了github，邮件上也不会有。。。。。。传到GitHub上


[test.zip](https://github.com/DLTech21/ofd.js/files/5432261/test.zip)

**Comment by DLTech21** [comment]
代码已修复
