### ISSUE TITLE
当contentDiv设置固定高度时，白色背景高度发生自适应。

### ISSUE THREAD

**Issue by 719034075** [DLTech21/ofd.js#29]
## 官方DEMO中，contentDiv的height是随着OFD具体内容自适应变化的。
![image](https://user-images.githubusercontent.com/17671135/98508926-4c481600-229b-11eb-9bc0-02dc164cb05f.png)

## 当我希望给contentDiv一个固定height，且超出部分以显示滚动条的形式展示时。ODF的白色纸张高度会收缩，但是文字位置正常。
![image](https://user-images.githubusercontent.com/17671135/98509098-98935600-229b-11eb-9edb-f53db32fa067.png)

![image](https://user-images.githubusercontent.com/17671135/98509376-0b9ccc80-229c-11eb-901c-ffa742ae8faf.png)

![image](https://user-images.githubusercontent.com/17671135/98509407-1c4d4280-229c-11eb-949b-add1fe5d8369.png)

**Comment by DLTech21** [comment]
![image](https://user-images.githubusercontent.com/2238211/98660945-d6b67580-2380-11eb-8f74-dc293090894c.png)
按照这个就可以实现你要的效果
