### ISSUE TITLE
如何访问本地文件？能有一个讨论群之类的吗

### ISSUE THREAD

**Issue by zkhh666** [DLTech21/ofd.js#37]
有点困惑，如何访问本地文件，资料也太少了。能有一个群解答一下吗

**Comment by zkhh666** [comment]
undefined is not iterable

**Comment by zkhh666** [comment]
that is not defined
at XMLHttpRequest.xhr.onreadystatechange

**Comment by zkhh666** [comment]
二进制怎么扔进去啊

**Comment by DLTech21** [comment]
请看demo，谢谢
