### ISSUE TITLE
webpack打包问题

### ISSUE THREAD

**Issue by relaxed-afternoon** [DLTech21/ofd.js#39]
webpack打包时，ofd.js需要babel转译才能打包成功。这里是否可以优化一下，改成不用功babel转译即可的？

**Comment by DLTech21** [comment]
一起重构纯js版本

**Comment by Insistem** [comment]
我发现使用Rollup打包，总是打包不成功，引用的npm包中有各种稀奇古怪的写法，最终还是用webpack打包了一下，打包成一个库文件。目前你提供的这个，只能通过 npm包的方式引入，没办法通过一个js文件的方式引入哈。不知道作者有没有打包成功过

**Comment by DLTech21** [comment]
后面会提供sdk的方式

**Comment by DLTech21** [comment]
> 我发现使用Rollup打包，总是打包不成功，引用的npm包中有各种稀奇古怪的写法，最终还是用webpack打包了一下，打包成一个库文件。目前你提供的这个，只能通过 npm包的方式引入，没办法通过一个js文件的方式引入哈。不知道作者有没有打包成功过

已支持

**Comment by Insistem** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
