### ISSUE TITLE
部分ODF文件查看之章是黑白的章

### ISSUE THREAD

**Issue by liulangren7** [DLTech21/ofd.js#45]
![image](https://user-images.githubusercontent.com/64702420/114803196-9fd20900-9dd1-11eb-8321-3c76cb4d9880.png)
部分ODF文件查看之章是黑白的章

**Comment by roy19831015** [comment]
> ![image](https://user-images.githubusercontent.com/64702420/114803196-9fd20900-9dd1-11eb-8321-3c76cb4d9880.png)
> 部分ODF文件查看之章是黑白的章

请提供测试用例，即OFD文件。

**Comment by liulangren7** [comment]
这是在线预览测试时显示黑色的章OFD文件zip
[445.zip](https://github.com/DLTech21/ofd.js/files/6314924/445.zip)

**Comment by liulangren7** [comment]
> > ![image](https://user-images.githubusercontent.com/64702420/114803196-9fd20900-9dd1-11eb-8321-3c76cb4d9880.png)
> > 部分ODF文件查看之章是黑白的章
> 
> 请提供测试用例，即OFD文件。



这是在线预览测试时显示黑色的章OFD文件zip
[445.zip](https://github.com/DLTech21/ofd.js/files/6314960/445.zip)

**Comment by DLTech21** [comment]
默认是黑色了，没考虑电票章是红色

**Comment by DLTech21** [comment]
黑色的原因是验签是无效的，自动变灰色
