### ISSUE TITLE
链接打不开

### ISSUE THREAD

**Issue by lunxian8** [DLTech21/ofd.js#47]
这样的地址：
http://172.16.10.65:9000/summer-dev/document/202107061350102921.ofd?Content-Disposition=attachment%3B%20filename%3D%22document%2F202107061350102921.ofd%22&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20210707%2F%2Fs3%2Faws4_request&X-Amz-Date=20210707T054904Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=6da04041cb073d02143d43174d741f67e51050a7beaa1b52317d173f71ea1ef5

![image](https://user-images.githubusercontent.com/27261113/124706654-3c67fb00-df2a-11eb-91d7-7698ad98a426.png)

**Comment by DLTech21** [comment]
自行改造支持url地址吧
