### ISSUE TITLE
ofd打开文字位置不对问题

### ISSUE THREAD

**Issue by shuirengu** [DLTech21/ofd.js#53]
浏览器: 谷歌&360急速
ofd.js版本: 最新版
打开后截图:
![image](https://user-images.githubusercontent.com/48910853/134270229-e179213b-f175-4245-9a91-2d22a05e8783.png)
原ofd截图:
![image](https://user-images.githubusercontent.com/48910853/134270283-b5144e2c-7955-4eff-9109-151c3751a527.png)
原ofd文件:
[keyword.zip](https://github.com/DLTech21/ofd.js/files/7207169/keyword.zip)

**Comment by DLTech21** [comment]
我debug看看

**Comment by shuirengu** [comment]
辛苦作者了。

**Comment by DLTech21** [comment]
加入我的知识星球支持下~~

**Comment by shuirengu** [comment]
放大缩小也有问题   好像就是整个文件放大或缩小后红色背景板没有变化导致的

**Comment by DLTech21** [comment]
我大概知道什么问题，有空优化吧

**Comment by shuirengu** [comment]
是因为ofd里面文字是放大或缩小了的 但是图片没有按比例放大或缩小导致的  渲染的时候直接就是百分比等比渲染的~~

**Comment by shuirengu** [comment]
![image](https://user-images.githubusercontent.com/48910853/135062875-79e98ac2-934d-4062-97cf-5a4828a2c906.png)
请问一下这个0.2642是咋来了啊

**Comment by DLTech21** [comment]
这个数字是有问题的

**Comment by shuirengu** [comment]
![image](https://user-images.githubusercontent.com/48910853/135196582-d7f93de7-42b5-4ed7-b5e3-2e6340f54cf7.png)
我改成这样已解决. 试了几个ofd。 按照ofd文档来看CTM的数值就是图片要显示的真实宽高，在乘以我们自己的放大倍数就可以了吧。不知道我这样思考对不对。。

**Comment by DLTech21** [comment]
不对

**Comment by DLTech21** [comment]
没考虑旋转
