### ISSUE TITLE
对于存在内置字体、多个资源索引文件的ofd文件无法显示

### ISSUE THREAD

**Issue by spenggch** [DLTech21/ofd.js#54]
对于存在内置字体、多个资源索引文件的ofd文件无法显示

[abc99.zip](https://github.com/DLTech21/ofd.js/files/7308508/abc99.zip)

**Comment by DLTech21** [comment]
![image](https://user-images.githubusercontent.com/2238211/140271185-b85b14f5-12d5-468b-9297-d0a98ca35d70.png)
已解决
