### ISSUE TITLE
SVG中image无法铺满

### ISSUE THREAD

**Issue by 409086114** [DLTech21/ofd.js#56]
OFD文件签署中，印章尺寸被强制改变（如：印章尺寸为40*30被改写成40*40），渲染之后显示印章图片还是原始尺寸40*30，这种情况应该进行修复。
@DLTech21

**Comment by DLTech21** [comment]
ofd发上来

**Comment by 409086114** [comment]
附件为：电子印章尺寸被强制改变并进行签署的OFD文件


------------------------------------------------------------------
发件人：Donal ***@***.***>
发送时间：2021年11月9日(星期二) 18:34
收件人：DLTech21/ofd.js ***@***.***>
抄　送：默 ***@***.***>; Author ***@***.***>
主　题：Re: [DLTech21/ofd.js] SVG中image无法铺满 (Issue #56)

ofd发上来
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DLTech21** [comment]
没看到印章的ofd

**Comment by 409086114** [comment]
当前截图为wps打开ofd文件展示效果，文件内是有变形章的


------------------------------------------------------------------
发件人：Donal ***@***.***>
发送时间：2021年11月10日(星期三) 14:22
收件人：DLTech21/ofd.js ***@***.***>
抄　送：默 ***@***.***>; Author ***@***.***>
主　题：Re: [DLTech21/ofd.js] SVG中image无法铺满 (Issue #56)

没看到印章的ofd
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DLTech21** [comment]
![image](https://user-images.githubusercontent.com/2238211/141061464-88715121-a759-4b1f-8fb3-ca7d2b142ab0.png)
发的是什么啊，没有截图，没有ofd

**Comment by 409086114** [comment]
我是使用邮箱进行回复的，github目前不支持ofd文件上传

**Comment by DLTech21** [comment]
zip即可

**Comment by 409086114** [comment]
附件为：电子印章尺寸被强制改变并进行签署的OFD文件及wps展示效果
[变形章文件及WPS展示效果.zip](https://github.com/DLTech21/ofd.js/files/7510417/WPS.zip)

**Comment by DLTech21** [comment]
![image](https://user-images.githubusercontent.com/2238211/141070830-646af230-20ac-4be8-a48a-f42ba2a03978.png)
