### ISSUE TITLE
纯文字OFD文件打开白屏问题

### ISSUE THREAD

**Issue by 409086114** [DLTech21/ofd.js#57]
ofd文件为纯文字文件，文件大小为9MB左右，文件内页码1287页，现在一次性渲染无法进行打开疑似GPU超负荷，是否应配置分部渲染（如pdf.js首次加载10页，后续根据当前页面进行前后5页渲染，减少硬件依赖并提升用户体验），文件见附件。

[1287页.zip](https://github.com/DLTech21/ofd.js/files/7524328/1287.zip)

另能否开源小程序源码，学习开发一下

**Comment by DLTech21** [comment]
小程序不会开源的，

**Comment by DLTech21** [comment]
这个原因是两个：1、js解析这个1000多页的ofd已经用时130s，这效率太低了；2、解析已经把浏览器的大部分内存吃完，接下来js生成div及渲染直接oom。
优化方向ofd解析改用c实现即可

**Comment by DLTech21** [comment]
![9d30599a3742c63acfc5159813c39ad](https://user-images.githubusercontent.com/2238211/142961662-9e64e7a2-041b-4376-9127-37f646c42a6a.png)

**Comment by DLTech21** [comment]
> ofd文件为纯文字文件，文件大小为9MB左右，文件内页码1287页，现在一次性渲染无法进行打开疑似GPU超负荷，是否应配置分部渲染（如pdf.js首次加载10页，后续根据当前页面进行前后5页渲染，减少硬件依赖并提升用户体验），文件见附件。
> 
> [1287页.zip](https://github.com/DLTech21/ofd.js/files/7524328/1287.zip)
> 
> 另能否开源小程序源码，学习开发一下

1287页渲染稍微优化了用户体验

**Comment by DLTech21** [comment]
可以去线上demo看看
