### ISSUE TITLE
数科的ofd在网页上找在线预览有印章，用这个ofd.js的demo打开ofd不显示印章是怎么回事

### ISSUE THREAD

**Issue by godlift** [DLTech21/ofd.js#59]

**Comment by godlift** [comment]
是因为stamp.sealObj.type === 'bmp'不支持，希望大佬可以支持下

**Comment by DLTech21** [comment]
发ofd文件debug看看

**Comment by godlift** [comment]
我在修改ofd_parse.js doGetRoot 方法后已经可以正常显示bmp的印章了  添加了 || stamp.sealObj.type === 'bmp'这个判断

**Comment by DLTech21** [comment]
暂时可以这样处理，

**Comment by godlift** [comment]
你这边可以修复一下发到NPM吗 ，我这边有点难整

**Comment by godlift** [comment]
我从github直接install我fork的代码在nodemoudles里面不全不知道为什么

**Comment by DLTech21** [comment]
主要是我现在重心放到wasm方案了

**Comment by godlift** [comment]
好的，我弄好了，我自己打包发布到npm了

**Comment by DLTech21** [comment]
是你自己的npm吧
