### ISSUE TITLE
展示签章时候会遮盖下方字体

### ISSUE THREAD

**Issue by liangjiadi** [DLTech21/ofd.js#6]
![image](https://user-images.githubusercontent.com/44561008/93977870-bb31e400-fdad-11ea-9885-407fc4dc3860.png)

**Comment by DLTech21** [comment]
请上传ofd

**Comment by liangjiadi** [comment]
[bdcdjzm_301213AF0610489FBEC46E8AB9C5C25F.zip](https://github.com/DLTech21/ofd.js/files/5266231/bdcdjzm_301213AF0610489FBEC46E8AB9C5C25F.zip)

**Comment by DLTech21** [comment]
![image](https://user-images.githubusercontent.com/2238211/93989082-110d8880-fdbc-11ea-8b70-105c61a487de.png)
asn1把章取出来发现就是有背景色的不，这种不处理
