### ISSUE TITLE
pipeline.js里在Array原型链上定义的pipeline导致项目所有的for in 都无法正常使用,    排查了好久

### ISSUE THREAD

**Issue by i-ce-fish** [DLTech21/ofd.js#61]
建议pipeline定义为不可枚举
` Object.defineProperty(Array.prototype, 'pipeline', {
      enumerable: false
    })`

![image](https://user-images.githubusercontent.com/26164421/146171434-615b4c3f-ce7f-4a02-9a86-ad15efc3e184.png)

**Comment by i-ce-fish** [comment]
但还是不建议使用for in来循环数组

**Comment by DLTech21** [comment]
新方案会采用wasm解决
