### ISSUE TITLE
国密验签显示签名值验证失败

### ISSUE THREAD

**Issue by whisper0429** [DLTech21/ofd.js#62]
@roy19831015 
   

> 我在使用项目显示并验签生成的OFD文档时，提示签名值验证失败。
![2021-12-21_234222](https://user-images.githubusercontent.com/39996925/146957934-c18a285d-078e-4860-a2cf-11778142f3a0.png)
> 使用数科的阅读器可以验签成功，另外这个文件就是使用数科的服务生成出来的。
> 注意到签名值前多了02，代码中是去掉的00，我修改后去掉02后也不能成功。
`           if(sigValueHex.indexOf('00')==0){
                sigValueHex = sigValueHex.substr(2,sigValueHex.length-2);
            }`
![2021-12-21_234634](https://user-images.githubusercontent.com/39996925/146958584-347c9c5b-7316-4b4b-8fa2-6948453c3c18.png)
> 研究了一下午，也没太清楚，感觉SES_Signature_Verify方法中的调用参数userId有关系。不知道这个id代表什么。

> 改了这个id后，项目自带的演示发票也验签失败了。

 ` sm2.doVerifySignature(msg, sigValueHex, publicKey, {
                der : true,
                hash: true,
                userId:"1234567812345678"}`

> 附上原文件，请帮忙看看是什么情况。
[2020010272000600086900000000043540122236009_外围.zip](https://github.com/DLTech21/ofd.js/files/7756541/2020010272000600086900000000043540122236009_.zip)

**Comment by DLTech21** [comment]
已解决
