### ISSUE TITLE
运行项目报错

### ISSUE THREAD

**Issue by rookieChenSir** [DLTech21/ofd.js#66]
当我使用npm run dev [启动我自己做的集成ofd.js的项目时报错，提示ses_signature_parser.js文件中的decodeSES_Signature方法报错。

![微信图片_20220124170138](https://user-images.githubusercontent.com/50978112/150753008-6bccec04-289c-4777-80c6-f843c2ca55da.png)

**Comment by DLTech21** [comment]
更新使用wasm
