### ISSUE TITLE
红色印章位置和大小不正确

### ISSUE THREAD

**Issue by unicorn1984** [DLTech21/ofd.js#69]
红色印章位置和大小不正确
![1647410183(1)](https://user-images.githubusercontent.com/7955357/158525761-b1946a43-9099-4a67-add7-51cf6e3f1b01.png)

**Comment by unicorn1984** [comment]
有问题的发票：
[ofd2.zip](https://github.com/DLTech21/ofd.js/files/8259291/ofd2.zip)

**Comment by DLTech21** [comment]
可以兼容，不过这样的ofd印章确实不好

**Comment by DLTech21** [comment]
![image](https://user-images.githubusercontent.com/2238211/158755047-bf60c44d-28f4-425c-a19a-b276739c0c1e.png)
