### ISSUE TITLE
ReferenceError: Module is not defined

### ISSUE THREAD

**Issue by liqifena** [DLTech21/ofd.js#71]
![image](https://user-images.githubusercontent.com/29426330/169250465-c8c9534a-2357-4107-92c3-c65c99feba92.png)

**Comment by liqifena** [comment]
0.8.5版本报这个错

**Comment by DLTech21** [comment]
没有在html引入OfdParser.js，具体看example

**Comment by liqifena** [comment]
> 没有在html引入OfdParser.js，具体看例子

![image](https://user-images.githubusercontent.com/29426330/169428758-9edbd9ba-f1b6-457f-a19c-bea471838dec.png)
引入后报这个错

**Comment by liqifena** [comment]
![image](https://user-images.githubusercontent.com/29426330/169430598-a2076e76-8b28-4377-b7c1-f8fda952fba2.png)

用0.2.5版本就可以，但是返回值好像不太对

**Comment by liqifena** [comment]
![image](https://user-images.githubusercontent.com/29426330/169435011-18c2fbb9-5b3c-4710-a3bd-f6c8eed3168d.png)
传入url，arraybuffer 都报这个错

**Comment by DLTech21** [comment]
加微信
