### ISSUE TITLE
用react import { openOFDBaseViewer } from "ofd.js";有问题，导入都导入不了，

### ISSUE THREAD

**Issue by Yangbg2018** [DLTech21/ofd.js#72]
![图片](https://user-images.githubusercontent.com/37174045/170411153-618d1564-70de-4d16-8b75-34529e808426.png)

**Comment by DLTech21** [comment]
加微信

**Comment by Yangbg2018** [comment]
> 

qq号多少，大老

**Comment by DLTech21** [comment]
readme有微信二维码

**Comment by Yangbg2018** [comment]
大佬qq号多少，我加下



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DLTech21/ofd.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 中午11:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DLTech21/ofd.js] 用react import { openOFDBaseViewer } from "ofd.js";有问题，导入都导入不了， (Issue #72)





 
加微信

**Comment by DLTech21** [comment]
541815852
