### ISSUE TITLE
ofd展示有重影

### ISSUE THREAD

**Issue by thwchao** [DLTech21/ofd.js#78]
![Dingtalk_20220812155757](https://user-images.githubusercontent.com/13268274/184310918-d172ee5b-87d5-4507-bb3f-b224a5f9cb89.jpg)
加载原文展示有重影https://raw.githubusercontent.com/thwchao/test/main/920E24C204554212B5282CCD6D2113BA.zip

**Comment by DLTech21** [comment]
加微信 techage21
