### ISSUE TITLE
印章有白色背景，在福昕上是透明的

### ISSUE THREAD

**Issue by WadonLiu** [DLTech21/ofd.js#8]
感谢作者的分享，写的很好。

ofd_parser.js  里印章    stamp.sealObj.type === ‘png’  的话, uint8转换base64的图片是有白色背景的，而在福昕上是看透明的。

所以我使用这个方法又转了一次图片，不知道有没有更好的办法

```
function changeImage(dataImg, callback) {
	let self = this;
	var base64Img = document.createElement("base64Img"),
		canvas = document.createElement("canvas"),
		context = canvas.getContext("2d");
	// 创建新图片
	var img = new Image();
	var baseImg;
	img.src = dataImg;
	img.addEventListener(
		"load",
		function () {
			// 绘制图片到canvas上
			canvas.width = img.width;
			canvas.height = img.height;
			context.drawImage(img, 0, 0);

			// 将canvas的透明背景设置成白色
			var imageData = context.getImageData(
				0,
				0,
				canvas.width,
				canvas.height
			);
			for (var i = 0; i < imageData.data.length; i += 4) {
				//rgb大于250的透明度y均设置成0
				if (
					imageData.data[i] > 250 &&
					imageData.data[i + 1] > 250 &&
					imageData.data[i + 2] > 250
				) {
					imageData.data[i + 3] = 0;
				}
			}
			context.putImageData(imageData, 0, 0);
			baseImg = canvas.toDataURL("image/png").slice(22);//返回base64
			if (typeof callback !== undefined) {
				if (callback) callback(baseImg);
			}
		},
		false
	);
}
```

**Comment by roy19831015** [comment]
你这个应该称作是，容差为5的PNG强制透明处理。
但我们的关注点不在如何处理这种情况，而在于应不应该处理。
主要的疑虑在于，将白色或者接近于白色的部分处理掉是否全部能够适用，比如底色为深色，图案为浅色时可能会把图案本身处理掉。
我们计划未来通过按钮或外部接口参数的方式将这个透明处理的决定权交给集成ofdjs的人或者是用户。

**Comment by DLTech21** [comment]
@WadonLiu 
![image](https://user-images.githubusercontent.com/2238211/94233979-60c68e00-ff3b-11ea-80b4-c2b24f1b8af4.png)

有空你可以做成这样

**Comment by little-me** [comment]
> 感谢作者的分享，写的很好。
> 
> ofd_parser.js 里印章 stamp.sealObj.type === ‘png’ 的话, uint8转换base64的图片是有白色背景的，而在福昕上是看透明的。
> 
> 所以我使用这个方法又转了一次图片，不知道有没有更好的办法
> 
> ```
> function changeImage(dataImg, callback) {
> 	let self = this;
> 	var base64Img = document.createElement("base64Img"),
> 		canvas = document.createElement("canvas"),
> 		context = canvas.getContext("2d");
> 	// 创建新图片
> 	var img = new Image();
> 	var baseImg;
> 	img.src = dataImg;
> 	img.addEventListener(
> 		"load",
> 		function () {
> 			// 绘制图片到canvas上
> 			canvas.width = img.width;
> 			canvas.height = img.height;
> 			context.drawImage(img, 0, 0);
> 
> 			// 将canvas的透明背景设置成白色
> 			var imageData = context.getImageData(
> 				0,
> 				0,
> 				canvas.width,
> 				canvas.height
> 			);
> 			for (var i = 0; i < imageData.data.length; i += 4) {
> 				//rgb大于250的透明度y均设置成0
> 				if (
> 					imageData.data[i] > 250 &&
> 					imageData.data[i + 1] > 250 &&
> 					imageData.data[i + 2] > 250
> 				) {
> 					imageData.data[i + 3] = 0;
> 				}
> 			}
> 			context.putImageData(imageData, 0, 0);
> 			baseImg = canvas.toDataURL("image/png").slice(22);//返回base64
> 			if (typeof callback !== undefined) {
> 				if (callback) callback(baseImg);
> 			}
> 		},
> 		false
> 	);
> }
> ```

实际使用也使用这样的思路解决了印章白色底板的问题，但是手机（小屏）上展示，印章变模糊，需要更改这个地方的代码，就可以解决问题了：
`canvas.width = img.width;
 canvas.height = img.height;`

`canvas.width = img.naturalWidth;
 canvas.height = img.naturalHeight;`

**Comment by DLTech21** [comment]
后续可能使用c处理
