### ISSUE TITLE
前端预览 直接clone下来 也无法打开ofd

### ISSUE THREAD

**Issue by wanghaonan-jiaojiao** [DLTech21/ofd.js#83]
![image](https://user-images.githubusercontent.com/56459224/209495998-15e05382-e7a3-46cc-a1b7-4d353646da91.png)
[
![image](https://user-images.githubusercontent.com/56459224/209496040-2eae25e5-67f4-478b-9356-685fb721f9f0.png)
![image](https://user-images.githubusercontent.com/56459224/209496063-6ddb5a38-e521-46e0-8298-40f5ad7db4aa.png)
![image](https://user-images.githubusercontent.com/56459224/209496070-0d40deb7-5485-4809-942f-bf51b05fd0b0.png)

**Comment by DLTech21** [comment]
自行debug
