### ISSUE TITLE
直接使用代码

### ISSUE THREAD

**Issue by xiuminLee** [DLTech21/ofd.js#84]
直接使用代码

_Originally posted by @DLTech21 in https://github.com/DLTech21/ofd.js/issues/82#issuecomment-1327298899_

**Comment by xiuminLee** [comment]
您好，能够具体说一下吗，前端如何去掉这个水印，代码怎么写，我看您的文档你们并没有说明

**Comment by DLTech21** [comment]
加微信

**Comment by mashize-m** [comment]
你好，前端同样遇到了水印问题，请问是如何处理的？
