### ISSUE TITLE
签章无法显示

### ISSUE THREAD

**Issue by Jonathan-Rao** [DLTech21/ofd.js#88]
![image](https://github.com/DLTech21/ofd.js/assets/16660755/9f7cd243-c2fb-4d5d-9ca6-13890284a7b6)

![image](https://github.com/DLTech21/ofd.js/assets/16660755/c152fc72-18d6-4628-ba97-ae2d7cff4f35)

**Comment by WednesdayCAT** [comment]
这个问题是因为签章后的OFD版式文件格式不一致，原本ofd.js中的签章渲染逻辑目录结构不对导致的。有相同问题的小伙伴可以看一下我的改过的ofd.js，解决了两个问题：

ofd文档打开报错；
ofd文档签章内容不显示。
