### ISSUE TITLE
未显示发票章

### ISSUE THREAD

**Issue by zhengdeding** [DLTech21/ofd.js#9]
红色签章未显示，麻烦帮忙看一下哪里的问题，新手上路，烦请指导，多谢！

![image](https://user-images.githubusercontent.com/18633371/94358419-72db3480-00d3-11eb-9056-29637aa4f551.png)

![image](https://user-images.githubusercontent.com/18633371/94358045-a8cae980-00d0-11eb-903c-66e43d956383.png)

![image](https://user-images.githubusercontent.com/18633371/94357139-bbd9bb80-00c8-11eb-8344-fcec26be9b11.png)

**Comment by DLTech21** [comment]
发ofd上来

**Comment by zhengdeding** [comment]
999.ofd一样的效果，好像是我本地的TypeError, 请问如何fix？    初学者，见谅：）

**Comment by zhengdeding** [comment]
好像是和 ses_signature_parser.js 中的stream和问号符有关，请问其中的问号可以去掉么？

我去掉了问号，服务才能正常启动vue：    

![image](https://user-images.githubusercontent.com/18633371/94358456-ad44d180-00d3-11eb-8bd2-f3dd574f2e78.png)

保留问号时候，编译错误，无法启动vue：

![image](https://user-images.githubusercontent.com/18633371/94358740-a5862c80-00d5-11eb-8022-599f817792c0.png)

**Comment by DLTech21** [comment]
不能去掉，那个是判断是否存在该节点

**Comment by zhengdeding** [comment]
多谢！ 再请教一下，问号应该设置在哪里，编译才能通过？

**Comment by roy19831015** [comment]
请还原代码后，尝试升级你的编译器。
